import React from 'react';
import { Member, Expense, ExpenseType, MessSummary } from '../types.ts';
import { formatCurrency } from '../utils/calculations.ts';

interface FullMessReportProps {
  summary: MessSummary;
  expenses: Expense[];
  currencyCode: string;
  reportId: string;
}

const FullMessReport: React.FC<FullMessReportProps> = ({ summary, expenses, currencyCode, reportId }) => {
  return (
    <div 
      id={reportId} 
      className="bg-white p-8 w-[800px] border border-slate-200"
      style={{ fontFamily: "'Inter', sans-serif" }}
    >
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-indigo-600 pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-black text-slate-900 mb-1">মেছ হিসাব বিবরণী (সম্পূর্ণ)</h1>
          <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">মাসের সকল হিসাবের সারসংক্ষেপ</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-black text-slate-900">{new Date().toLocaleDateString('bn-BD')}</p>
          <p className="text-[10px] text-slate-400 font-bold uppercase">Generated by Mess Tracker</p>
        </div>
      </div>

      {/* Main Summary Stats */}
      <div className="grid grid-cols-2 gap-6 mb-8">
        <div className="bg-indigo-700 rounded-2xl p-6 text-white shadow-lg">
          <p className="text-[10px] font-black uppercase tracking-widest opacity-80 mb-1">মোট দোকান বাকি</p>
          <h2 className="text-4xl font-black">{formatCurrency(summary.grandTotalDebt, currencyCode)}</h2>
          <div className="mt-4 grid grid-cols-2 gap-2">
            <div className="bg-white/10 p-2 rounded-xl">
              <p className="text-[8px] font-black opacity-60 uppercase">শেয়ার বাজার</p>
              <p className="text-sm font-black">{formatCurrency(summary.totalSharedExpense, currencyCode)}</p>
            </div>
            <div className="bg-white/10 p-2 rounded-xl">
              <p className="text-[8px] font-black opacity-60 uppercase">ব্যক্তিগত খরচ</p>
              <p className="text-sm font-black">{formatCurrency(summary.totalPersonalExpense, currencyCode)}</p>
            </div>
          </div>
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-4 flex flex-col justify-center">
            <p className="text-[10px] font-black text-emerald-600 uppercase mb-1">মোট জমা</p>
            <p className="text-xl font-black text-emerald-700">{formatCurrency(summary.totalPayments, currencyCode)}</p>
          </div>
          <div className="bg-amber-50 border border-amber-100 rounded-2xl p-4 flex flex-col justify-center">
            <p className="text-[10px] font-black text-amber-600 uppercase mb-1">মোট নাস্তা জমা</p>
            <p className="text-xl font-black text-amber-700">{formatCurrency(summary.totalBreakfastPayments, currencyCode)}</p>
          </div>
          <div className="bg-slate-50 border border-slate-100 rounded-2xl p-4 flex flex-col justify-center col-span-2">
            <p className="text-[10px] font-black text-slate-500 uppercase mb-1">গড় শেয়ার খরচ (জনপ্রতি)</p>
            <p className="text-xl font-black text-slate-700">{formatCurrency(summary.averagePerPerson, currencyCode)}</p>
          </div>
        </div>
      </div>

      {/* Member Balances Table */}
      <div className="mb-10">
        <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
          <span className="w-2 h-6 bg-indigo-600 rounded-full"></span>
          মেম্বার ভিত্তিক হিসাব
        </h3>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 border-y border-slate-200">
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">মেম্বার</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">শেয়ার</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">ব্যক্তিগত</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">জমা</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">ব্যালেন্স</th>
            </tr>
          </thead>
          <tbody>
            {summary.memberBalances.map((mb, idx) => (
              <tr key={mb.member.id} className={`border-b border-slate-100 ${idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/30'}`}>
                <td className="py-3 px-4">
                  <div className="flex items-center gap-2">
                    <img src={mb.member.avatar} className="w-6 h-6 rounded-full bg-slate-100" />
                    <span className="text-[12px] font-black text-slate-800">{mb.member.name}</span>
                  </div>
                </td>
                <td className="py-3 px-4 text-right text-[11px] font-bold text-slate-600">
                  {formatCurrency(mb.sharedShare, currencyCode)}
                </td>
                <td className="py-3 px-4 text-right text-[11px] font-bold text-slate-600">
                  {formatCurrency(mb.personalTotal, currencyCode)}
                </td>
                <td className="py-3 px-4 text-right text-[11px] font-bold text-emerald-600">
                  {formatCurrency(mb.paid, currencyCode)}
                </td>
                <td className={`py-3 px-4 text-right text-[12px] font-black ${mb.netBalance < 0 ? 'text-rose-600' : 'text-emerald-600'}`}>
                  {formatCurrency(mb.netBalance, currencyCode)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Recent Transactions (Optional, maybe just a few) */}
      <div>
        <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
          <span className="w-2 h-6 bg-indigo-600 rounded-full"></span>
          সাম্প্রতিক লেনদেন (শেষ ১০টি)
        </h3>
        <div className="space-y-2">
          {expenses.slice(0, 10).map((exp) => (
            <div key={exp.id} className="flex justify-between items-center p-3 bg-slate-50 rounded-xl border border-slate-100">
              <div>
                <p className="text-[11px] font-black text-slate-800">{exp.description}</p>
                <p className="text-[8px] text-slate-400 font-bold uppercase">{new Date(exp.date).toLocaleDateString('bn-BD')}</p>
              </div>
              <p className={`text-[11px] font-black ${exp.type === ExpenseType.PAYMENT ? 'text-emerald-600' : 'text-rose-600'}`}>
                {exp.type === ExpenseType.PAYMENT ? '+' : '-'}{formatCurrency(exp.amount, currencyCode)}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-12 pt-8 border-t border-slate-200 text-center">
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">
          ধন্যবাদ • ব্যাচেলর দের মেছের হিসাব
        </p>
      </div>
    </div>
  );
};

export default FullMessReport;
