import React from 'react';
import { Member, Expense, ExpenseType, MemberBalance } from '../types.ts';
import { formatCurrency } from '../utils/calculations.ts';

interface MemberReportProps {
  memberBalance: MemberBalance;
  expenses: Expense[];
  currencyCode: string;
  reportId: string;
}

const MemberReport: React.FC<MemberReportProps> = ({ memberBalance, expenses, currencyCode, reportId }) => {
  const { member } = memberBalance;
  
  // Filter expenses related to this member
  const memberExpenses = expenses.filter(e => 
    e.targetMemberId === member.id || e.type === ExpenseType.SHARED
  ).sort((a, b) => b.date - a.date);

  return (
    <div 
      id={reportId} 
      className="bg-white p-8 w-[800px] border border-slate-200"
      style={{ fontFamily: "'Inter', sans-serif" }}
    >
      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-indigo-600 pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-black text-slate-900 mb-1">মেছ হিসাব রিপোর্ট</h1>
          <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">ব্যক্তিগত লেনদেন খাতা</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-black text-slate-900">{new Date().toLocaleDateString('bn-BD')}</p>
          <p className="text-[10px] text-slate-400 font-bold uppercase">Generated by Mess Tracker</p>
        </div>
      </div>

      {/* Summary Stats - Moved to top */}
      <div className="grid grid-cols-4 gap-4 mb-8">
        <div className="bg-white border border-slate-100 rounded-xl p-4 text-center shadow-sm">
          <p className="text-[10px] font-black text-slate-400 uppercase mb-1">মোট জমা</p>
          <p className="text-lg font-black text-emerald-600">{formatCurrency(memberBalance.paid, currencyCode)}</p>
        </div>
        <div className="bg-white border border-slate-100 rounded-xl p-4 text-center shadow-sm">
          <p className="text-[10px] font-black text-slate-400 uppercase mb-1">বাজার শেয়ার</p>
          <p className="text-lg font-black text-indigo-600">{formatCurrency(memberBalance.sharedShare, currencyCode)}</p>
        </div>
        <div className="bg-white border border-slate-100 rounded-xl p-4 text-center shadow-sm">
          <p className="text-[10px] font-black text-slate-400 uppercase mb-1">ব্যক্তিগত খরচ</p>
          <p className="text-lg font-black text-rose-600">{formatCurrency(memberBalance.personalTotal, currencyCode)}</p>
        </div>
        <div className="bg-white border border-slate-100 rounded-xl p-4 text-center shadow-sm">
          <p className="text-[10px] font-black text-slate-400 uppercase mb-1">নাস্তা জমা</p>
          <p className="text-lg font-black text-amber-600">{formatCurrency(memberBalance.breakfastPaid, currencyCode)}</p>
        </div>
      </div>

      {/* Member Info Card */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        <div className="bg-slate-50 rounded-2xl p-6 border border-slate-100 flex items-center gap-4">
          <img src={member.avatar} className="w-20 h-20 rounded-full border-4 border-white shadow-md bg-white" />
          <div>
            <h2 className="text-2xl font-black text-slate-900">{member.name}</h2>
            <p className="text-xs font-bold text-indigo-600 uppercase tracking-wider">
              {member.leaveDate ? 'নিষ্ক্রিয় মেম্বার' : 'সক্রিয় মেম্বার'}
            </p>
            <p className="text-[10px] text-slate-400 mt-1">যোগদান: {new Date(member.joinDate).toLocaleDateString('bn-BD')}</p>
          </div>
        </div>

        <div className="bg-indigo-600 rounded-2xl p-6 text-white shadow-lg flex flex-col justify-center">
          <p className="text-[10px] font-black uppercase tracking-widest opacity-80 mb-1">বর্তমান ব্যালেন্স</p>
          <h3 className="text-4xl font-black">
            {formatCurrency(memberBalance.netBalance, currencyCode)}
          </h3>
          <p className={`text-[10px] font-bold mt-2 ${memberBalance.netBalance < 0 ? 'text-rose-200' : 'text-emerald-200'}`}>
            {memberBalance.netBalance < 0 ? 'মেছ আপনার কাছে পাবে' : 'আপনি মেছের কাছে পাবেন'}
          </p>
        </div>
      </div>

      {/* Transaction Table */}
      <div>
        <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
          <span className="w-2 h-6 bg-indigo-600 rounded-full"></span>
          লেনদেন এর বিস্তারিত
        </h3>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 border-y border-slate-200">
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">তারিখ</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">বিবরণ</th>
              <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">ধরণ</th>
              <th className="py-3 px-4 text-right text-[10px] font-black text-slate-500 uppercase tracking-widest">পরিমাণ</th>
            </tr>
          </thead>
          <tbody>
            {memberExpenses.map((exp, idx) => {
              let typeLabel = "শেয়ার";
              let typeColor = "text-indigo-600 bg-indigo-50";
              
              if (exp.type === ExpenseType.PERSONAL) {
                typeLabel = "ব্যক্তিগত";
                typeColor = "text-rose-600 bg-rose-50";
              } else if (exp.type === ExpenseType.PAYMENT) {
                typeLabel = exp.description.includes("নাস্তা") ? "নাস্তা" : "জমা";
                typeColor = "text-emerald-600 bg-emerald-50";
              }

              return (
                <tr key={exp.id} className={`border-b border-slate-100 ${idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/30'}`}>
                  <td className="py-3 px-4 text-[11px] font-bold text-slate-500">
                    {new Date(exp.date).toLocaleDateString('bn-BD')}
                  </td>
                  <td className="py-3 px-4 text-[12px] font-black text-slate-800">
                    {exp.description}
                  </td>
                  <td className="py-3 px-4">
                    <span className={`text-[9px] font-black uppercase px-2 py-1 rounded-md ${typeColor}`}>
                      {typeLabel}
                    </span>
                  </td>
                  <td className={`py-3 px-4 text-right text-[12px] font-black ${exp.type === ExpenseType.PAYMENT ? 'text-emerald-600' : 'text-rose-600'}`}>
                    {exp.type === ExpenseType.PAYMENT ? '+' : '-'}{formatCurrency(exp.amount, currencyCode)}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Footer */}
      <div className="mt-12 pt-8 border-t border-slate-200 text-center">
        <div className="flex flex-col items-center gap-2 mb-4">
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">ডেবলপার এর সাথে যোগাযোগ করুন</p>
          <div className="flex gap-4">
            <p className="text-[10px] font-bold text-blue-600">Facebook: fb.com/billal8795</p>
            <p className="text-[10px] font-bold text-emerald-600">WhatsApp: +8801735308795</p>
          </div>
        </div>
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">
          ধন্যবাদ • ব্যাচেলর দের মেছের হিসাব
        </p>
      </div>
    </div>
  );
};

export default MemberReport;
